### ISSUE TITLE
Wrong current total

### ISSUE THREAD

**Issue by dnldd** [planetdecred/dcrandroid#513] opened 2020-09-05 12:47 UTC
My mobile wallet has been stuck reporting wrong current total amounts for a bit now, I suspect its because some transactions from the app's perspective are still pending when they are actually not. I have confirmed these pending on decrediton to have been processed. Please consider adding wallet rescan functionality while you fix these issues, thanks.
![Screenshot_20200905-120442~2](https://user-images.githubusercontent.com/1281030/92305329-baa7e980-ef75-11ea-9f02-a5f937269026.jpg)

![Screenshot_20200905-121827~2](https://user-images.githubusercontent.com/1281030/92305331-bc71ad00-ef75-11ea-8905-4122dd236b4b.jpg)

**Comment by C-ollins** [comment] 2020-09-07 05:05
You can do a rescan. It’s under Wallet Settings in Wallets tab https://github.com/planetdecred/dcrandroid/pull/414.

**Comment by C-ollins** [comment] 2020-09-07 05:07
The total balance bug has been fixed in https://github.com/planetdecred/dcrlibwallet/pull/155.

**Comment by dnldd** [comment] 2020-09-07 12:34
> You can do a rescan. It’s under Wallet Settings in Wallets tab #414.

This isn't available in the current release, consider putting out a hotfix if the scheduled release is not close.

**Comment by C-ollins** [comment] 2020-09-07 21:19
It's available in the latest release (https://github.com/planetdecred/dcrandroid/releases/tag/v1.5.0). It was tagged 30th May 2020 and #414 was merged 29th December 2019.

**Comment by dnldd** [comment] 2020-09-07 21:51
Gotcha, wasn't looking at the right place. Thanks.

**Comment by raedah** [comment] 2020-09-07 23:07
I dont find the settings per wallet to be ideal, and we can look for another way. One thing to consider is that we dont want required rescan's to be an expected behavior for users. The feature should be used as a last resorting in debugging. Normal wallet behavior should be to do proper accounting. In the case of the bug you encountered, a rescan does not help because the bug was caused by the app not properly updating the UI. An easier debugging work around is to close and reopen the app, or take any other action that would cause the apps page to refresh. The patched update will be released shortly.

**Comment by raedah** [comment] 2020-09-09 22:53
closed by https://github.com/planetdecred/dcrandroid/pull/494

**Closed by raedah** 2020-09-09 22:53 UTC
