### ISSUE TITLE
Add Tickets Page and View

### ISSUE THREAD

**Issue by dnldd** [planetdecred/dcrandroid#512] opened 2020-09-05 12:10 UTC
A tickets view on the overview page which would have a "see more" link to a tickets page for in-depth information on tickets (immature, voted, total rewards etc) would be a nice addition.

**Comment by dreacot** [comment] 2021-09-21 14:29
duplicate of https://github.com/planetdecred/dcrandroid/issues/266

**Closed by dreacot** 2021-09-21 14:29 UTC
